#!/usr/bin/env python3
"""
extract.py — CS2 Minneapolis Services Pipeline (Sesión 3)
==========================================================
Extrae los servicios públicos reales desde OpenStreetMap y los exporta como
un archivo JS listo para el visualizador Leaflet (overlay encima de los mapas
de zonificación y vial existentes).

Salida (`visualizer/datos_servicios.js`):
    const DATA_SERVICES_POLYGONS = {
      health:    [{ id, name, subtype, coords, tags }, ...],
      education: [...], fire: [...], admin: [...], parks: [...],
    };
    const DATA_SERVICES_POINTS = {
      health:    [{ id, name, subtype, coord, tags }, ...],
      education: [...], fire: [...], admin: [...], parks: [...],
    };
    const DATA_SERVICES_META = { bbox, generated_at, total_features };

Uso:
    cd src
    uv run extract-services
    uv run extract-services --bbox "44.86,-93.38,45.05,-93.17"
    uv run extract-services --out ../visualizer/datos_servicios.js
"""

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from shared.overpass_client import query_with_retry
from services.classifiers import classify_service, infer_geometry_kind
from services.zones import SERVICES_LABELS, MINNEAPOLIS_BBOX, build_services_query


# ── Feature assembly ─────────────────────────────────────────────────────────

def make_feature(element: dict, cat: str, kind: str) -> dict:
    """
    Construye el dict de feature para el output JS.

    Para kind='polygon': incluye 'coords' como lista de [lat, lon].
    Para kind='point': incluye 'coord' como [lat, lon] (centroide o primer nodo).
    """
    tags = element.get("tags") or {}
    subtype = (tags.get("amenity") or tags.get("leisure") or tags.get("landuse")
               or tags.get("office") or tags.get("tourism") or "")

    feat = {
        "id": element["id"],
        "name": tags.get("name", ""),
        "subtype": subtype,
        "tags": dict(tags),
    }

    if kind == "polygon":
        geom = element.get("geometry") or []
        feat["coords"] = [[pt["lat"], pt["lon"]] for pt in geom]
    else:  # point
        if element["type"] == "node":
            feat["coord"] = [element["lat"], element["lon"]]
        else:
            # way clasificado como point (geometría corta o no cerrada) —
            # usar primer nodo como anchor
            geom = element.get("geometry") or []
            if geom:
                feat["coord"] = [geom[0]["lat"], geom[0]["lon"]]
            else:
                feat["coord"] = [0.0, 0.0]  # fallback defensivo

    return feat


# ── Pipeline ─────────────────────────────────────────────────────────────────

def run(bbox: str, out_path: Path) -> dict:
    """
    Ejecuta el pipeline completo: query → classify → split → write.

    Devuelve dict de meta para tests/logging.
    """
    query = build_services_query(bbox)

    # Buckets: cat → {polygon: [...], point: [...]}
    polygons: dict[str, list] = defaultdict(list)
    points: dict[str, list] = defaultdict(list)
    skipped_class = 0

    result = query_with_retry(query, "services")
    elements = result.get("elements", [])

    for el in elements:
        tags = el.get("tags") or {}
        cat = classify_service(tags, el["type"])
        if cat is None:
            skipped_class += 1
            continue
        kind = infer_geometry_kind(el)
        feat = make_feature(el, cat, kind)
        if kind == "polygon":
            polygons[cat].append(feat)
        else:
            points[cat].append(feat)

    # Asegurar las 5 claves siempre presentes
    for key in SERVICES_LABELS:
        polygons.setdefault(key, [])
        points.setdefault(key, [])

    total = sum(len(v) for v in polygons.values()) + sum(len(v) for v in points.values())

    meta = {
        "bbox": bbox,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_features": total,
    }

    # ── Write output ─────────────────────────────────────────────────────────
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by extract-services — do not edit manually\n")
        f.write(f"// {meta['generated_at']} — {total} features — bbox {bbox}\n\n")
        f.write("const DATA_SERVICES_POLYGONS = ")
        json.dump(dict(polygons), f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n\n")
        f.write("const DATA_SERVICES_POINTS = ")
        json.dump(dict(points), f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n\n")
        f.write("const DATA_SERVICES_META = ")
        json.dump(meta, f, ensure_ascii=False)
        f.write(";\n")

    return {
        "polygons": polygons,
        "points": points,
        "meta": meta,
        "skipped_class": skipped_class,
    }


# ── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Extract OSM public services for CS2 Minneapolis (Sesión 3)"
    )
    parser.add_argument(
        "--bbox",
        default=MINNEAPOLIS_BBOX,
        help=f"Bounding box 'south,west,north,east' (default: {MINNEAPOLIS_BBOX})",
    )
    parser.add_argument(
        "--out",
        default="../visualizer/datos_servicios.js",
        help="Output .js file path",
    )
    args = parser.parse_args()

    bbox = args.bbox
    out_path = Path(args.out)

    print("CS2 Minneapolis Services Extractor — Sesión 3")
    print(f"Bounding Box : {bbox}")
    print(f"Output       : {out_path}\n")

    print("[1/2] Downloading services from Overpass...")
    summary = run(bbox=bbox, out_path=out_path)

    print("\n[2/2] Splitting features into 5 CS2 buckets...")
    print()
    print(f"  {'category':<12}  polygons  points")
    print(f"  {'-'*12}  {'-'*8}  {'-'*6}")
    for key in SERVICES_LABELS:
        p = len(summary["polygons"].get(key, []))
        n = len(summary["points"].get(key, []))
        print(f"  {key:<12}  {p:>8}  {n:>6}")
    print(f"  {'-'*12}  {'-'*8}  {'-'*6}")
    total = summary["meta"]["total_features"]
    print(f"  {'TOTAL':<12}  {total:>17}")
    print(f"\n  skipped (no classifier): {summary['skipped_class']}")
    print(f"\n[OK] Wrote {out_path} ({out_path.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
